labels:
  - name: '🐛 bug'
    color: 'bd0a29'
    description: "Something isn't working."
  - name: '✨ enhancement'
    color: 'a8e6cf'
    description: 'New feature or improvement of an existing one.'
  - name: '✍️ docs'
    color: '7003bd'
    description: 'Improvements or additions to the documentation.'
  - name: '❔ question'
    color: 'ffd3b6'
    description: 'Further information is requested.'
  - name: '🐣 good first issue'
    color: 'c5def5'
    description: 'A great starting point for newcomers.'
  - name: '🤗 help wanted'
    color: 'fef2c0'
    description: 'Assistance is appreciated.'
  - name: '🙏 help wanted'
    color: 'dcedc1'
    description: 'Some description.'
  - name: '❌ wontfix'
    color: '000000'
    description: "This won't be worked on."
  - name: '👥 duplicate'
    color: '000000'
    description: 'A similar pull request or issue exists already.'
