name: publish

on:
  workflow_dispatch:
    inputs:
      kind:
        description: 'Kind of release'
        default: 'minor'
        type: choice
        options:
        - prepatch
        - patch
        - preminor
        - minor
        - premajor
        - major
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: publish
        name: Publish release
        uses: boywithkeyboard/taco@v1
        with:
          kind: ${{github.event.inputs.kind}}

      - name: Bump major version
        run: |
          full="${{ steps.publish.outputs.tag_name }}"
          short="${full:0:2}"
          git tag $short -f
          git push --tags -f
